spring:
  application:
    name: catalog-service # ?? ???? ??? ????? ? ???? application name
  config:
    import: "optional:configserver:" # ???? config server?? ?? ???? ????.
  cloud:
    config:
      uri: http://localhost:8888 # Config Server's URL
      request-connect-timeout: 5000 # Config server? ??? ??? ???? ?? (ms)
      request-read-timeout: 5000 # Config server?? ?? ???? ?? ??? ???? ?? (ms)
      fail-fast: true # ?? ?? ?? ??? ??? ??? ??, ??? ??? ? ??? true? ??? ???? ?????.
      retry:
        max-attempts: 6 # ?? retry ?? ??
        initial-interval: 1000 # ?? retry ?? ?? (ms)
        max-interval: 2000 # retry ?? ?? ?? (ms)
        multiplier: 1.1 # ?? ?? ?? ??

server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout:
    threads:
      max: 50
      min-spare: 5

polar:
  greeting: Welcome to the local book catalog!

management:
  endpoints:
    web:
      exposure:
        include: refresh # /actuator/refresh ?????? ????? ???


